[features]
seeds = false
skip-lint = false

# [programs.devnet]
# counter_anchor = "DzJQf39X1SF13WYX8LX34ZRA2Pfm55MXKsPByz8hWxvz"

[registry]
#url = "https://api.apr.dev"
url = "https://solana-devnet.g.alchemy.com/v2/dx_EaB8ZVmi7hYiAYrXQ20x1GgizekQH"

[provider]
cluster = "Localnet"
#cluster = "https://api.tatum.io/v3/blockchain/node/solana-devnet"
wallet = "~/.config/solana/id.json"
#skippreflight = true

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
